// 自動產生：node scripts/gen-icons.mjs
import type { Component } from 'vue'
import {
  Radar as I_Radar,
  UserSearch as I_UserSearch,
  PhoneCall as I_PhoneCall,
  Bot as I_Bot,
  Bug as I_Bug,
  Fish as I_Fish,
  Drama as I_Drama,
  KeyRound as I_KeyRound,
  Hammer as I_Hammer,
  DoorOpen as I_DoorOpen,
  BellRing as I_BellRing,
  Terminal as I_Terminal,
  Puzzle as I_Puzzle,
  Usb as I_Usb,
  BugPlay as I_BugPlay,
  Network as I_Network,
  Siren as I_Siren,
  DatabaseBackup as I_DatabaseBackup,
  LockKeyhole as I_LockKeyhole,
  Banknote as I_Banknote,
  Send as I_Send,
  MousePointerClick as I_MousePointerClick,
  MonitorOff as I_MonitorOff,
  Copy as I_Copy,
  Handshake as I_Handshake,
  Share2 as I_Share2,
  HeartHandshake as I_HeartHandshake,
  ThumbsUp as I_ThumbsUp,
  Key as I_Key,
  Waves as I_Waves,
  Hourglass as I_Hourglass,
  Globe as I_Globe,
  EyeOff as I_EyeOff,
  Users as I_Users,
  DatabaseZap as I_DatabaseZap,
  FileText as I_FileText,
  Cloud as I_Cloud,
  KeySquare as I_KeySquare,
  UserX as I_UserX,
  PackagePlus as I_PackagePlus,
  MessageSquareWarning as I_MessageSquareWarning,
  GraduationCap as I_GraduationCap,
  Wrench as I_Wrench,
  Smartphone as I_Smartphone,
  BrickWall as I_BrickWall,
  MailWarning as I_MailWarning,
  UserPlus as I_UserPlus,
  CalendarClock as I_CalendarClock,
  Scissors as I_Scissors,
  Eye as I_Eye,
  Ghost as I_Ghost,
  Factory as I_Factory,
  Rocket as I_Rocket,
  Hospital as I_Hospital,
  School as I_School,
  ShieldCheck as I_ShieldCheck,
  ShieldX as I_ShieldX,
  ShieldAlert as I_ShieldAlert,
  ShieldOff as I_ShieldOff,
  Zap as I_Zap,
  Lock as I_Lock,
  LockOpen as I_LockOpen,
  Skull as I_Skull,
  Snowflake as I_Snowflake,
  Volume2 as I_Volume2,
  VolumeX as I_VolumeX,
  Settings as I_Settings,
  CircleQuestionMark as I_CircleQuestionMark,
  Crosshair as I_Crosshair,
  Activity as I_Activity,
  Building2 as I_Building2,
  X as I_X,
  Check as I_Check,
  ChevronRight as I_ChevronRight,
  Info as I_Info,
  RotateCcw as I_RotateCcw,
  Play as I_Play,
  Trophy as I_Trophy,
  Sparkles as I_Sparkles,
  Flame as I_Flame,
  Clock as I_Clock,
  Layers as I_Layers,
  ArrowRight as I_ArrowRight,
  FastForward as I_FastForward,
  History as I_History,
  UserRound as I_UserRound,
  TriangleAlert as I_TriangleAlert,
  CircleAlert as I_CircleAlert,
  HardDrive as I_HardDrive,
  Server as I_Server,
  Database as I_Database,
  Cpu as I_Cpu,
  Recycle as I_Recycle,
  Mail as I_Mail,
  ScanEye as I_ScanEye,
  Lightbulb as I_Lightbulb,
  BookOpen as I_BookOpen,
  ListChecks as I_ListChecks,
  Flag as I_Flag,
  Target as I_Target,
  Swords as I_Swords,
  Crown as I_Crown,
  HandCoins as I_HandCoins,
  Timer as I_Timer,
  Menu as I_Menu,
  Pause as I_Pause,
  Shuffle as I_Shuffle,
  Hand as I_Hand,
  Scan as I_Scan,
  Download as I_Download,
  ServerCrash as I_ServerCrash,
  ScrollText as I_ScrollText,
  Eraser as I_Eraser,
  Waypoints as I_Waypoints,
  PackageSearch as I_PackageSearch,
  Coffee as I_Coffee,
  PiggyBank as I_PiggyBank,
} from 'lucide-vue-next'

export const ICONS: Record<string, Component> = {
  'radar': I_Radar,
  'user-search': I_UserSearch,
  'phone-call': I_PhoneCall,
  'bot': I_Bot,
  'bug': I_Bug,
  'fish': I_Fish,
  'drama': I_Drama,
  'key-round': I_KeyRound,
  'hammer': I_Hammer,
  'door-open': I_DoorOpen,
  'bell-ring': I_BellRing,
  'terminal': I_Terminal,
  'puzzle': I_Puzzle,
  'usb': I_Usb,
  'bug-play': I_BugPlay,
  'network': I_Network,
  'siren': I_Siren,
  'database-backup': I_DatabaseBackup,
  'lock-keyhole': I_LockKeyhole,
  'banknote': I_Banknote,
  'send': I_Send,
  'mouse-pointer-click': I_MousePointerClick,
  'monitor-off': I_MonitorOff,
  'copy': I_Copy,
  'handshake': I_Handshake,
  'share-2': I_Share2,
  'heart-handshake': I_HeartHandshake,
  'thumbs-up': I_ThumbsUp,
  'key': I_Key,
  'waves': I_Waves,
  'hourglass': I_Hourglass,
  'globe': I_Globe,
  'eye-off': I_EyeOff,
  'users': I_Users,
  'database-zap': I_DatabaseZap,
  'file-text': I_FileText,
  'cloud': I_Cloud,
  'key-square': I_KeySquare,
  'user-x': I_UserX,
  'package-plus': I_PackagePlus,
  'message-square-warning': I_MessageSquareWarning,
  'graduation-cap': I_GraduationCap,
  'wrench': I_Wrench,
  'smartphone': I_Smartphone,
  'brick-wall': I_BrickWall,
  'mail-warning': I_MailWarning,
  'user-plus': I_UserPlus,
  'calendar-clock': I_CalendarClock,
  'scissors': I_Scissors,
  'eye': I_Eye,
  'ghost': I_Ghost,
  'factory': I_Factory,
  'rocket': I_Rocket,
  'hospital': I_Hospital,
  'school': I_School,
  'shield-check': I_ShieldCheck,
  'shield-x': I_ShieldX,
  'shield-alert': I_ShieldAlert,
  'shield-off': I_ShieldOff,
  'zap': I_Zap,
  'lock': I_Lock,
  'lock-open': I_LockOpen,
  'skull': I_Skull,
  'snowflake': I_Snowflake,
  'volume-2': I_Volume2,
  'volume-x': I_VolumeX,
  'settings': I_Settings,
  'circle-question-mark': I_CircleQuestionMark,
  'crosshair': I_Crosshair,
  'activity': I_Activity,
  'building-2': I_Building2,
  'x': I_X,
  'check': I_Check,
  'chevron-right': I_ChevronRight,
  'info': I_Info,
  'rotate-ccw': I_RotateCcw,
  'play': I_Play,
  'trophy': I_Trophy,
  'sparkles': I_Sparkles,
  'flame': I_Flame,
  'clock': I_Clock,
  'layers': I_Layers,
  'arrow-right': I_ArrowRight,
  'fast-forward': I_FastForward,
  'history': I_History,
  'user-round': I_UserRound,
  'triangle-alert': I_TriangleAlert,
  'circle-alert': I_CircleAlert,
  'hard-drive': I_HardDrive,
  'server': I_Server,
  'database': I_Database,
  'cpu': I_Cpu,
  'recycle': I_Recycle,
  'mail': I_Mail,
  'scan-eye': I_ScanEye,
  'lightbulb': I_Lightbulb,
  'book-open': I_BookOpen,
  'list-checks': I_ListChecks,
  'flag': I_Flag,
  'target': I_Target,
  'swords': I_Swords,
  'crown': I_Crown,
  'hand-coins': I_HandCoins,
  'timer': I_Timer,
  'menu': I_Menu,
  'pause': I_Pause,
  'shuffle': I_Shuffle,
  'hand': I_Hand,
  'scan': I_Scan,
  'download': I_Download,
  'server-crash': I_ServerCrash,
  'scroll-text': I_ScrollText,
  'eraser': I_Eraser,
  'waypoints': I_Waypoints,
  'package-search': I_PackageSearch,
  'coffee': I_Coffee,
  'piggy-bank': I_PiggyBank,
}
